import React, { useState, useEffect, useRef } from "react";
import { createRoot } from "react-dom/client";
import { GoogleGenAI, Type } from "@google/genai";
import { 
  LineChart, 
  Search, 
  PieChart, 
  Activity, 
  Layers, 
  TrendingUp, 
  TrendingDown,
  Minus,
  AlertTriangle, 
  MessageSquare,
  ArrowRight,
  ShieldAlert,
  User,
  LogOut,
  History,
  X,
  Lock,
  Mail,
  Upload,
  Image as ImageIcon,
  Clock,
  CheckCircle,
  Info,
  ExternalLink,
  ChevronRight,
  HelpCircle,
  Target,
  Zap,
  BrainCircuit
} from "lucide-react";

// --- Types ---
interface CompanyData {
  name: string;
  ticker: string;
  summary: string;
  sector: string;
  businessScope: string;
  financialHighlights: {
    peRatio: string;
    pbRatio: string;
    marketCap: string;
    revenue: string;
    netIncome: string;
    grossMargin: string;
    debtToAsset: string;
  };
  risks: string[];
  prediction?: {
    targetPrice: string;
    trend: "Bullish" | "Bearish" | "Neutral";
    confidence: number;
    horizon: string;
    reasoning: string;
  };
  sources?: { title: string; uri: string }[];
}

interface ChatMessage {
  role: "user" | "model";
  text: string;
}

interface UserProfile {
  email: string;
  username: string;
  password?: string; 
  avatar?: string; // Base64 string
  history: string[];
  createdAt: number;
}

// --- Constants ---
const METRIC_DEFINITIONS: Record<string, string> = {
  "P/E Ratio": "The Price-to-Earnings (P/E) ratio measures a company's current share price relative to its per-share earnings. It helps investors determine if a stock is overvalued or undervalued compared to its earnings.",
  "P/B Ratio": "The Price-to-Book (P/B) ratio compares a company's market capitalization to its book value. It is often used to identify undervalued stocks.",
  "Market Cap": "Market Capitalization is the total dollar market value of a company's outstanding shares of stock. It indicates the size of a company in the financial markets.",
  "Revenue": "Revenue is the total amount of income generated by the sale of goods or services related to the company's primary operations before any expenses are deducted.",
  "Net Income": "Net Income is the total profit of the company after all expenses, including cost of goods sold, operating expenses, taxes, and interest, have been deducted from revenue.",
  "Gross Margin": "Gross Margin represents the portion of each dollar of revenue that the company retains as gross profit (Revenue minus Cost of Goods Sold). It indicates manufacturing efficiency.",
  "Debt-to-Asset": "The Debt-to-Asset ratio indicates the proportion of a company's assets that are financed with debt. A higher ratio suggests higher financial leverage and potentially higher risk."
};

const INDICATOR_DEFINITIONS: Record<string, string> = {
  "MA5": "5-Day Moving Average: Shows the average closing price over the last 5 days. Useful for identifying short-term price trends.",
  "MA20": "20-Day Moving Average: Shows the average closing price over the last 20 days. Helps identify medium-term support and resistance levels.",
  "RSI": "Relative Strength Index (14): A momentum oscillator that measures the speed and change of price movements. Values above 70 indicate overbought conditions, while below 30 indicate oversold.",
  "MACD": "Moving Average Convergence Divergence: A trend-following momentum indicator that shows the relationship between two moving averages of a security's price.",
  "Volume": "Trading Volume: The total number of shares or contracts traded during a specified timeframe. High volume often confirms the strength of a trend.",
  "Stoch": "Stochastic Oscillator (%K): A momentum indicator comparing a closing price to a price range over time. Values > 80 indicate overbought, < 20 oversold.",
  "Bollinger": "Bollinger Bands: A volatility indicator. The display shows the Upper and Lower bands. Prices near the Upper Band may indicate overbought conditions."
};

// --- API Service ---
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

// --- Mock Data Generator ---
const generateMockStockData = (basePrice: number, points: number) => {
  let price = basePrice;
  const data = [];
  const now = new Date();
  
  for (let i = 0; i < points; i++) {
    const change = (Math.random() - 0.5) * (basePrice * 0.05);
    price += change;
    const date = new Date(now);
    date.setDate(date.getDate() - (points - i));
    
    // Calculate simulated indicators
    const rsi = 30 + Math.random() * 40; 
    const macd = (Math.random() - 0.5) * 2;
    const stochK = Math.max(0, Math.min(100, 50 + (Math.random() - 0.5) * 80));
    
    // Bollinger Bands mock
    const volatility = price * 0.05;
    const bollUpper = price + volatility;
    const bollLower = price - volatility;
    
    data.push({
      date: date.toLocaleDateString(undefined, { month: 'short', day: 'numeric' }),
      price: Math.max(0.1, price),
      volume: Math.floor(Math.random() * 1000000) + 500000,
      ma5: price * (1 + (Math.random() - 0.5) * 0.02),
      ma20: price * (1 + (Math.random() - 0.5) * 0.05),
      rsi,
      macd,
      stochK,
      bollUpper,
      bollLower
    });
  }
  return data;
};

// --- IndexedDB & Auth Utilities ---
const DB_NAME = 'AlphaAnalystDB';
const DB_VERSION = 1;
const STORE_USERS = 'users';
const SESSION_KEY = 'alpha_analyst_session_user';

// Database Helper Class
class LocalDB {
  private db: IDBDatabase | null = null;

  async init(): Promise<void> {
    return new Promise((resolve, reject) => {
      const request = indexedDB.open(DB_NAME, DB_VERSION);

      request.onerror = () => reject("Database failed to open");
      
      request.onsuccess = (event) => {
        this.db = (event.target as IDBOpenDBRequest).result;
        resolve();
      };

      request.onupgradeneeded = (event) => {
        const db = (event.target as IDBOpenDBRequest).result;
        if (!db.objectStoreNames.contains(STORE_USERS)) {
          // Use email as the unique key
          db.createObjectStore(STORE_USERS, { keyPath: 'email' });
        }
      };
    });
  }

  async getUser(email: string): Promise<UserProfile | undefined> {
    return new Promise((resolve, reject) => {
      if (!this.db) return reject("DB not initialized");
      const transaction = this.db.transaction([STORE_USERS], 'readonly');
      const store = transaction.objectStore(STORE_USERS);
      const request = store.get(email);
      
      request.onsuccess = () => resolve(request.result);
      request.onerror = () => reject("Failed to get user");
    });
  }

  async saveUser(user: UserProfile): Promise<void> {
    return new Promise((resolve, reject) => {
      if (!this.db) return reject("DB not initialized");
      const transaction = this.db.transaction([STORE_USERS], 'readwrite');
      const store = transaction.objectStore(STORE_USERS);
      const request = store.put(user);
      
      request.onsuccess = () => resolve();
      request.onerror = () => reject("Failed to save user");
    });
  }
}

const dbService = new LocalDB();

const generateCode = () => Math.floor(100000 + Math.random() * 900000).toString();

const validatePassword = (pwd: string) => {
  const hasLength = pwd.length >= 8;
  const hasLetters = /[a-zA-Z]/.test(pwd);
  const hasNumbers = /\d/.test(pwd);
  const hasSpecial = /[!@#$%^&*(),.?":{}|<>]/.test(pwd);
  
  const typesCount = [hasLetters, hasNumbers, hasSpecial].filter(Boolean).length;
  return hasLength && typesCount >= 2;
};

// --- Components ---

const SidebarItem = ({ icon: Icon, label, active, onClick, disabled = false }: { icon: any, label: string, active: boolean, onClick: () => void, disabled?: boolean }) => (
  <button
    onClick={disabled ? undefined : onClick}
    className={`w-full flex items-center space-x-3 px-4 py-3 rounded-lg transition-all duration-200 ${
      active 
        ? "bg-blue-500 text-white shadow-md" 
        : "text-gray-500 hover:bg-white hover:text-gray-900"
    } ${disabled ? "opacity-50 cursor-not-allowed" : "cursor-pointer"}`}
  >
    <Icon size={20} />
    <span className="font-medium text-sm">{label}</span>
  </button>
);

const Card = ({ children, className = "" }: { children?: React.ReactNode, className?: string }) => (
  <div className={`bg-white rounded-2xl p-6 card-shadow border border-gray-100 ${className}`}>
    {children}
  </div>
);

const MetricCard = ({ label, value, subtext, onClick }: { label: string, value: string, subtext?: string, onClick?: () => void }) => (
  <div 
    onClick={onClick}
    className={`p-4 bg-gray-50 rounded-xl h-full flex flex-col justify-center overflow-hidden relative group transition-all duration-200 ${
      onClick ? 'cursor-pointer hover:bg-blue-50 hover:shadow-sm border border-transparent hover:border-blue-100' : ''
    }`}
  >
    <div className="flex justify-between items-start mb-2">
      <div className="text-xs font-medium text-gray-500 uppercase tracking-wider truncate pr-2" title={label}>{label}</div>
      {onClick && <Info size={14} className="text-gray-300 group-hover:text-blue-500 transition-colors flex-shrink-0 opacity-0 group-hover:opacity-100" />}
    </div>
    <div className="text-base md:text-lg font-bold text-gray-900 break-words leading-tight" title={value}>
        {value}
    </div>
    {subtext && <div className="text-xs text-gray-400 mt-1 truncate" title={subtext}>{subtext}</div>}
  </div>
);

const HoverTooltip = ({ text, children }: { text: string, children: React.ReactNode }) => {
  const [isVisible, setIsVisible] = useState(false);
  
  return (
    <div 
      className="relative flex flex-col items-center group cursor-help"
      onMouseEnter={() => setIsVisible(true)}
      onMouseLeave={() => setIsVisible(false)}
    >
      {children}
      {isVisible && (
        <div className="absolute bottom-full mb-2 w-48 p-3 bg-gray-900/95 backdrop-blur text-white text-xs rounded-lg shadow-xl z-50 text-center animate-fade-in border border-gray-800 pointer-events-none">
          {text}
          <div className="absolute top-full left-1/2 transform -translate-x-1/2 border-4 border-transparent border-t-gray-900/95"></div>
        </div>
      )}
    </div>
  );
};

const PredictionCard = ({ prediction }: { prediction: CompanyData['prediction'] }) => {
  if (!prediction) return null;

  const isBullish = prediction.trend === "Bullish";
  const isBearish = prediction.trend === "Bearish";
  const trendColor = isBullish ? "text-green-600" : isBearish ? "text-red-600" : "text-gray-600";
  const bgColor = isBullish ? "bg-green-50" : isBearish ? "bg-red-50" : "bg-gray-50";
  const borderColor = isBullish ? "border-green-100" : isBearish ? "border-red-100" : "border-gray-200";
  
  const TrendIcon = isBullish ? TrendingUp : isBearish ? TrendingDown : Minus;

  return (
    <Card className={`w-full relative overflow-hidden`}>
      <div className="flex items-center space-x-3 mb-6">
        <div className={`p-2 rounded-lg ${bgColor} ${trendColor}`}>
          <BrainCircuit size={20} />
        </div>
        <div>
          <h2 className="text-xl font-semibold">AI Market Prediction</h2>
          <p className="text-xs text-gray-400">Model-generated forecast • {prediction.horizon} Horizon</p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-6">
        {/* Trend Indicator */}
        <div className={`p-4 rounded-xl border ${borderColor} ${bgColor} flex items-center justify-between`}>
          <div>
            <div className="text-xs font-medium uppercase tracking-wider opacity-70 mb-1">Trend</div>
            <div className={`text-xl font-bold ${trendColor}`}>{prediction.trend}</div>
          </div>
          <TrendIcon size={32} className={trendColor} />
        </div>

        {/* Target Price */}
        <div className="p-4 rounded-xl border border-gray-100 bg-gray-50 flex items-center justify-between">
           <div>
            <div className="text-xs font-medium text-gray-500 uppercase tracking-wider mb-1">Target Price</div>
            <div className="text-xl font-bold text-gray-900">{prediction.targetPrice}</div>
          </div>
          <Target size={28} className="text-blue-500" />
        </div>

        {/* Confidence Score */}
        <div className="p-4 rounded-xl border border-gray-100 bg-gray-50">
           <div className="flex justify-between items-center mb-2">
              <div className="text-xs font-medium text-gray-500 uppercase tracking-wider">AI Confidence</div>
              <div className="text-sm font-bold text-gray-900">{prediction.confidence}%</div>
           </div>
           <div className="w-full bg-gray-200 rounded-full h-2">
              <div 
                className="bg-blue-600 h-2 rounded-full transition-all duration-1000 ease-out" 
                style={{ width: `${prediction.confidence}%` }}
              ></div>
           </div>
        </div>
      </div>

      {/* Reasoning */}
      <div className="bg-gray-50 rounded-xl p-5 border border-gray-100">
        <h3 className="text-sm font-semibold text-gray-900 mb-2 flex items-center">
          <Zap size={16} className="text-yellow-500 mr-2" />
          Analysis & Reasoning
        </h3>
        <p className="text-sm text-gray-600 leading-relaxed">
          {prediction.reasoning}
        </p>
      </div>

      <div className="mt-6 p-4 bg-amber-50 border border-amber-100 rounded-xl flex items-start space-x-3">
         <ShieldAlert size={20} className="text-amber-600 shrink-0 mt-0.5" />
         <div className="text-sm text-amber-900 leading-relaxed">
           <span className="font-bold block mb-1 text-amber-700">Disclaimer: Automated Prediction</span>
           These forecasts are generated by AI models based on historical data patterns and do not constitute financial advice. Market conditions are volatile and subject to rapid change. We strongly recommend consulting with a qualified financial advisor before making any investment decisions.
         </div>
      </div>
    </Card>
  );
};

const SimpleChart = ({ data, color = "#0071E3" }: { data: any[], color?: string }) => {
  const [showMA5, setShowMA5] = useState(true);
  const [showMA20, setShowMA20] = useState(false);
  const [showBollinger, setShowBollinger] = useState(false);
  const [tooltip, setTooltip] = useState<{ x: number, y: number, data: any } | null>(null);

  if (!data || data.length === 0) return null;

  // SVG resolution (coordinate system)
  const width = 800;
  const height = 400;
  
  // Explicit margins to define the drawing area versus labels area
  const margin = { top: 20, right: 30, bottom: 50, left: 60 };
  const graphWidth = width - margin.left - margin.right;
  const graphHeight = height - margin.top - margin.bottom;

  // Calculate dynamic range based on visible lines
  const allPrices = data.flatMap(d => [
    d.price, 
    showMA5 ? d.ma5 : null, 
    showMA20 ? d.ma20 : null,
    showBollinger ? d.bollUpper : null,
    showBollinger ? d.bollLower : null
  ].filter(v => v !== null));
  
  const minPrice = Math.min(...allPrices);
  const maxPrice = Math.max(...allPrices);
  const priceRange = maxPrice - minPrice || 1;

  const getX = (index: number) => margin.left + (index / (data.length - 1)) * graphWidth;
  const getY = (price: number) => margin.top + graphHeight - ((price - minPrice) / priceRange) * graphHeight;

  const points = data.map((d, i) => `${getX(i)},${getY(d.price)}`).join(" ");
  const ma5Points = data.map((d, i) => `${getX(i)},${getY(d.ma5)}`).join(" ");
  const ma20Points = data.map((d, i) => `${getX(i)},${getY(d.ma20)}`).join(" ");

  // Bollinger Paths
  const bollUpperPoints = data.map((d, i) => `${getX(i)},${getY(d.bollUpper)}`).join(" ");
  const bollLowerPoints = data.map((d, i) => `${getX(i)},${getY(d.bollLower)}`).join(" ");
  const bollAreaPoints = [
      ...data.map((d, i) => `${getX(i)},${getY(d.bollUpper)}`),
      ...data.slice().reverse().map((d, i) => {
         const origIndex = data.length - 1 - i;
         return `${getX(origIndex)},${getY(d.bollLower)}`;
      })
  ].join(" ");

  const handleMouseMove = (e: React.MouseEvent<SVGSVGElement>) => {
    const svgRect = e.currentTarget.getBoundingClientRect();
    const mouseX = e.clientX - svgRect.left;
    const chartWidth = width - margin.left - margin.right;
    
    // Calculate index from mouse position relative to SVG scaling
    let index = Math.round(((mouseX * (width / svgRect.width)) - margin.left) / chartWidth * (data.length - 1));
    index = Math.max(0, Math.min(index, data.length - 1));
    
    const d = data[index];
    setTooltip({
      x: getX(index),
      y: getY(d.price),
      data: d
    });
  };

  // Determine tooltip alignment based on horizontal position
  const isRightSide = tooltip && tooltip.x > width / 2;

  return (
    <div className="w-full relative select-none group"> 
      <div className="w-full aspect-[2/1] relative overflow-hidden rounded-lg">
        <svg 
          viewBox={`0 0 ${width} ${height}`} 
          preserveAspectRatio="xMidYMid meet"
          className="w-full h-full cursor-crosshair"
          onMouseMove={handleMouseMove}
          onMouseLeave={() => setTooltip(null)}
        >
          {/* Grid lines */}
          <line x1={margin.left} y1={margin.top} x2={margin.left} y2={height - margin.bottom} stroke="#D1D1D6" strokeWidth="1" />
          <line x1={margin.left} y1={height - margin.bottom} x2={width - margin.right} y2={height - margin.bottom} stroke="#D1D1D6" strokeWidth="1" />
          <line x1={margin.left} y1={margin.top} x2={width - margin.right} y2={margin.top} stroke="#F2F2F7" strokeWidth="1" />
          
          {/* Bollinger Bands */}
          {showBollinger && (
            <>
               <polygon points={bollAreaPoints} fill="#3B82F6" fillOpacity="0.1" />
               <polyline points={bollUpperPoints} fill="none" stroke="#60A5FA" strokeWidth="1" strokeDasharray="2 2" />
               <polyline points={bollLowerPoints} fill="none" stroke="#60A5FA" strokeWidth="1" strokeDasharray="2 2" />
            </>
          )}

          {/* MA Lines */}
          {showMA5 && <polyline points={ma5Points} fill="none" stroke="#FF9500" strokeWidth="2" strokeDasharray="6 4" /> }
          {showMA20 && <polyline points={ma20Points} fill="none" stroke="#AF52DE" strokeWidth="2" strokeDasharray="6 4" />}
          
          {/* Price Line */}
          <polyline points={points} fill="none" stroke={color} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
          
          {/* Gradient */}
          <defs>
            <linearGradient id="gradient" x1="0" x2="0" y1="0" y2="1">
              <stop offset="0%" stopColor={color} stopOpacity="0.2" />
              <stop offset="100%" stopColor={color} stopOpacity="0" />
            </linearGradient>
          </defs>
          <polygon points={`${points} ${width-margin.right},${height-margin.bottom} ${margin.left},${height-margin.bottom}`} fill="url(#gradient)" />
          
          {/* Tooltip Indicators */}
          {tooltip && (
            <>
              <line 
                x1={tooltip.x} y1={margin.top} 
                x2={tooltip.x} y2={height - margin.bottom} 
                stroke="#999" strokeWidth="1.5" strokeDasharray="4 4" 
              />
              <circle cx={tooltip.x} cy={tooltip.y} r="5" fill={color} stroke="white" strokeWidth="2.5" />
            </>
          )}

          {/* Y Axis Labels */}
          <text x={margin.left - 15} y={getY(maxPrice)} textAnchor="end" dominantBaseline="middle" fontSize="13" fill="#8E8E93" fontWeight="500">{maxPrice.toFixed(2)}</text>
          <text x={margin.left - 15} y={getY(minPrice)} textAnchor="end" dominantBaseline="middle" fontSize="13" fill="#8E8E93" fontWeight="500">{minPrice.toFixed(2)}</text>
          
          {/* X Axis Labels */}
          <text x={width - margin.right} y={height - 20} textAnchor="end" fontSize="13" fill="#8E8E93" fontWeight="500">Today</text>
          <text x={margin.left} y={height - 20} textAnchor="start" fontSize="13" fill="#8E8E93" fontWeight="500">30 Days Ago</text>
        </svg>
      </div>

      {/* Tooltip Overlay - MOVED OUTSIDE OVERFLOW HIDDEN CONTAINER */}
      {tooltip && (
        <div 
          className="absolute bg-white/95 backdrop-blur shadow-2xl border border-gray-100 rounded-lg p-3 text-xs pointer-events-none z-50 transition-all duration-75 min-w-[150px]"
          style={{ 
            left: `${(tooltip.x / width) * 100}%`, 
            top: `${(tooltip.y / height) * 100}%`,
            transform: `translate(${isRightSide ? '-105%' : '5%'}, -50%)`, // Smart positioning: flip left if on right side
            marginTop: '-10px' // Slight offset
          }}
        >
          <div className="font-bold text-gray-900 mb-2 border-b border-gray-100 pb-1">{tooltip.data.date}</div>
          <div className="grid grid-cols-2 gap-x-4 gap-y-1">
            <div className="text-gray-500">Price</div>
            <div className="font-mono font-bold text-gray-900 text-right">{tooltip.data.price.toFixed(2)}</div>
            
            {showMA5 && (
              <>
                <div className="text-orange-500">MA5</div>
                <div className="font-mono font-medium text-orange-600 text-right">{tooltip.data.ma5.toFixed(2)}</div>
              </>
            )}
            
            {showMA20 && (
              <>
                <div className="text-purple-500">MA20</div>
                <div className="font-mono font-medium text-purple-600 text-right">{tooltip.data.ma20.toFixed(2)}</div>
              </>
            )}

            {showBollinger && (
              <>
                <div className="text-blue-500">Boll Up</div>
                <div className="font-mono font-medium text-blue-600 text-right">{tooltip.data.bollUpper.toFixed(2)}</div>
                <div className="text-blue-400">Boll Low</div>
                <div className="font-mono font-medium text-blue-400 text-right">{tooltip.data.bollLower.toFixed(2)}</div>
              </>
            )}
            
            <div className="text-gray-400">Vol</div>
            <div className="font-mono text-gray-500 text-right">{(tooltip.data.volume/1000).toFixed(0)}k</div>
            
             <div className="text-gray-400">RSI</div>
            <div className="font-mono text-gray-500 text-right">{tooltip.data.rsi.toFixed(1)}</div>
          </div>
        </div>
      )}

      <div className="flex justify-center space-x-6 mt-4 text-xs select-none">
        <div className="flex items-center">
          <span className="w-2.5 h-2.5 bg-[#0071E3] rounded-full mr-2"></span>
          <span className="font-medium text-gray-700">Price</span>
        </div>
        <button 
          onClick={() => setShowMA5(!showMA5)}
          className={`flex items-center transition-all duration-200 ${showMA5 ? 'opacity-100' : 'opacity-40 grayscale'}`}
        >
          <span className="w-2.5 h-2.5 bg-[#FF9500] rounded-full mr-2"></span>
          <HoverTooltip text={INDICATOR_DEFINITIONS['MA5']}>
            <span className="font-medium text-gray-700 border-b border-dashed border-gray-300">MA5</span>
          </HoverTooltip>
        </button>
        <button 
          onClick={() => setShowMA20(!showMA20)}
          className={`flex items-center transition-all duration-200 ${showMA20 ? 'opacity-100' : 'opacity-40 grayscale'}`}
        >
          <span className="w-2.5 h-2.5 bg-[#AF52DE] rounded-full mr-2"></span>
          <HoverTooltip text={INDICATOR_DEFINITIONS['MA20']}>
            <span className="font-medium text-gray-700 border-b border-dashed border-gray-300">MA20</span>
          </HoverTooltip>
        </button>
        <button 
          onClick={() => setShowBollinger(!showBollinger)}
          className={`flex items-center transition-all duration-200 ${showBollinger ? 'opacity-100' : 'opacity-40 grayscale'}`}
        >
          <span className="w-2.5 h-2.5 bg-[#60A5FA] rounded-full mr-2"></span>
          <HoverTooltip text={INDICATOR_DEFINITIONS['Bollinger']}>
            <span className="font-medium text-gray-700 border-b border-dashed border-gray-300">BOLL</span>
          </HoverTooltip>
        </button>
      </div>
    </div>
  );
};

// --- Modals ---

const Modal = ({ isOpen, onClose, children, title }: { isOpen: boolean, onClose: () => void, children?: React.ReactNode, title: string }) => {
  if (!isOpen) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center modal-overlay p-4">
      <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md overflow-hidden animate-fade-in">
        <div className="flex justify-between items-center p-4 border-b border-gray-100">
          <h3 className="text-lg font-semibold text-gray-900">{title}</h3>
          <button onClick={onClose} className="p-1 rounded-full hover:bg-gray-100 text-gray-500">
            <X size={20} />
          </button>
        </div>
        <div className="p-6">
          {children}
        </div>
      </div>
    </div>
  );
};

const AuthModal = ({ isOpen, onClose, onLoginSuccess }: { isOpen: boolean, onClose: () => void, onLoginSuccess: (user: UserProfile) => void }) => {
  const [mode, setMode] = useState<'login' | 'register' | 'forgot'>('login');
  const [step, setStep] = useState<1 | 2>(1); // 1: Input, 2: Verify Code
  
  // Form State
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [code, setCode] = useState('');
  const [generatedCode, setGeneratedCode] = useState('');
  const [demoCode, setDemoCode] = useState<string | null>(null); // For UI display
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const resetForm = () => {
    setEmail(''); setPassword(''); setConfirmPassword(''); setCode(''); setError(''); setStep(1); setLoading(false); setDemoCode(null);
  };

  // Reset to login mode and clear form when modal opens
  useEffect(() => {
    if (isOpen) {
      setMode('login');
      resetForm();
    }
  }, [isOpen]);

  // Handle clearing form when switching modes internally (if triggered by user click)
  useEffect(() => {
    if (isOpen) resetForm();
  }, [mode, isOpen]);


  const handleSendCode = async () => {
    if (!email.includes('@')) {
      setError("Please enter a valid email.");
      return;
    }
    setLoading(true);
    try {
      const existingUser = await dbService.getUser(email);

      if (mode === 'register' && existingUser) {
        setError("Account already exists.");
        setLoading(false);
        return;
      }
      if (mode === 'forgot' && !existingUser) {
        setError("Account not found.");
        setLoading(false);
        return;
      }

      const newCode = generateCode();
      setGeneratedCode(newCode);
      setDemoCode(newCode); // Set the code to be displayed in UI
      
      // Simulate network delay
      await new Promise(r => setTimeout(r, 800));
      
      setStep(2);
      setError('');
    } catch (e) {
      setError("Database error occurred.");
    } finally {
      setLoading(false);
    }
  };

  const handleRegister = async () => {
    if (code !== generatedCode) {
      setError("Invalid verification code.");
      return;
    }
    if (password !== confirmPassword) {
      setError("Passwords do not match.");
      return;
    }
    if (!validatePassword(password)) {
      setError("Password must be 8+ chars and contain at least 2 types of characters.");
      return;
    }

    setLoading(true);
    try {
      const newUser: UserProfile = {
        email,
        username: email.split('@')[0], 
        password, // In production, never store plaintext passwords
        history: [],
        createdAt: Date.now()
      };

      await dbService.saveUser(newUser);
      onLoginSuccess(newUser);
      onClose();
    } catch (e) {
      setError("Registration failed. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleLogin = async () => {
    setLoading(true);
    try {
      const user = await dbService.getUser(email);
      if (user && user.password === password) {
        onLoginSuccess(user);
        onClose();
      } else {
        setError("Invalid email or password.");
      }
    } catch (e) {
      setError("Login failed due to database error.");
    } finally {
      setLoading(false);
    }
  };

  const handleResetPassword = async () => {
    if (code !== generatedCode) {
      setError("Invalid verification code.");
      return;
    }
    if (password !== confirmPassword) {
      setError("Passwords do not match.");
      return;
    }
    if (!validatePassword(password)) {
      setError("Password requirements not met.");
      return;
    }

    setLoading(true);
    try {
      const user = await dbService.getUser(email);
      if (user) {
        user.password = password;
        await dbService.saveUser(user);
        alert("Password reset successfully. Please login.");
        setMode('login');
        resetForm();
      }
    } catch (e) {
      setError("Failed to update password.");
    } finally {
      setLoading(false);
    }
  };

  const inputClass = "w-full p-3 border border-gray-600 rounded-xl bg-gray-700 text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 transition-colors";

  return (
    <Modal isOpen={isOpen} onClose={onClose} title={mode === 'login' ? 'Welcome Back' : mode === 'register' ? 'Create Account' : 'Reset Password'}>
      <div className="space-y-4">
        {error && (
          <div className="flex items-center space-x-2 p-3 bg-red-50 text-red-600 text-sm rounded-lg animate-fade-in border border-red-100">
            <AlertTriangle size={16} className="shrink-0" />
            <span className="font-medium">{error}</span>
          </div>
        )}

        {mode === 'login' && (
          <>
            <input className={inputClass} placeholder="Email" value={email} onChange={e => setEmail(e.target.value)} autoComplete="off" />
            <input className={inputClass} type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)} autoComplete="new-password" />
            <button onClick={handleLogin} disabled={loading} className="w-full bg-blue-500 text-white p-3 rounded-xl hover:bg-blue-600 transition disabled:opacity-50">
              {loading ? 'Signing In...' : 'Sign In'}
            </button>
            <div className="flex justify-between text-sm mt-4">
              <button onClick={() => setMode('register')} className="text-blue-600">Create Account</button>
              <button onClick={() => setMode('forgot')} className="text-gray-500">Forgot Password?</button>
            </div>
          </>
        )}

        {mode === 'register' && (
          <>
            {step === 1 && (
              <>
                <input className={inputClass} placeholder="Email" value={email} onChange={e => setEmail(e.target.value)} autoComplete="off" />
                 <button onClick={handleSendCode} disabled={loading} className="w-full bg-blue-500 text-white p-3 rounded-xl hover:bg-blue-600 disabled:opacity-50">
                   {loading ? 'Sending...' : 'Send Verification Code'}
                 </button>
              </>
            )}
            {step === 2 && (
              <>
                {demoCode && (
                   <div className="mb-2 p-3 bg-blue-50 border border-blue-100 rounded-lg text-blue-900 text-sm flex items-start space-x-2">
                     <Info size={16} className="shrink-0 mt-0.5" />
                     <div>
                       <div className="font-semibold mb-1">Demo Environment</div>
                       <div>Since this is a client-side demo, we cannot send real emails.</div>
                       <div className="mt-2">Your verification code is: <span className="font-mono font-bold text-lg bg-white px-2 rounded border border-blue-200 select-all">{demoCode}</span></div>
                     </div>
                   </div>
                )}
                
                <input className={inputClass} placeholder="6-digit Code" value={code} onChange={e => setCode(e.target.value)} maxLength={6} autoComplete="off" />
                <input className={inputClass} type="password" placeholder="Password (8+ chars, mixed types)" value={password} onChange={e => setPassword(e.target.value)} autoComplete="new-password" />
                <input className={inputClass} type="password" placeholder="Confirm Password" value={confirmPassword} onChange={e => setConfirmPassword(e.target.value)} autoComplete="new-password" />
                <button onClick={handleRegister} disabled={loading} className="w-full bg-green-500 text-white p-3 rounded-xl hover:bg-green-600 disabled:opacity-50">
                  {loading ? 'Registering...' : 'Register & Login'}
                </button>
              </>
            )}
            <div className="text-center text-sm mt-4">
              <button onClick={() => { setMode('login'); setStep(1); }} className="text-blue-600">Back to Login</button>
            </div>
          </>
        )}

        {mode === 'forgot' && (
          <>
             {step === 1 && (
              <>
                <input className={inputClass} placeholder="Account Email" value={email} onChange={e => setEmail(e.target.value)} autoComplete="off" />
                 <button onClick={handleSendCode} disabled={loading} className="w-full bg-blue-500 text-white p-3 rounded-xl hover:bg-blue-600 disabled:opacity-50">
                    {loading ? 'Sending...' : 'Send Reset Code'}
                 </button>
              </>
            )}
            {step === 2 && (
              <>
                {demoCode && (
                   <div className="mb-2 p-3 bg-blue-50 border border-blue-100 rounded-lg text-blue-900 text-sm flex items-start space-x-2">
                     <Info size={16} className="shrink-0 mt-0.5" />
                     <div>
                       <div className="font-semibold mb-1">Demo Environment</div>
                       <div className="mt-2">Your reset code is: <span className="font-mono font-bold text-lg bg-white px-2 rounded border border-blue-200 select-all">{demoCode}</span></div>
                     </div>
                   </div>
                )}
                <input className={inputClass} placeholder="6-digit Code" value={code} onChange={e => setCode(e.target.value)} maxLength={6} autoComplete="off" />
                <input className={inputClass} type="password" placeholder="New Password" value={password} onChange={e => setPassword(e.target.value)} autoComplete="new-password" />
                <input className={inputClass} type="password" placeholder="Confirm New Password" value={confirmPassword} onChange={e => setConfirmPassword(e.target.value)} autoComplete="new-password" />
                <button onClick={handleResetPassword} disabled={loading} className="w-full bg-blue-500 text-white p-3 rounded-xl hover:bg-blue-600 disabled:opacity-50">
                  {loading ? 'Updating...' : 'Reset Password'}
                </button>
              </>
            )}
             <div className="text-center text-sm mt-4">
              <button onClick={() => { setMode('login'); setStep(1); }} className="text-gray-500">Cancel</button>
            </div>
          </>
        )}
      </div>
    </Modal>
  );
};

const ProfileModal = ({ user, isOpen, onClose, onUpdate, onLogout }: { user: UserProfile, isOpen: boolean, onClose: () => void, onUpdate: (u: UserProfile) => void, onLogout: () => void }) => {
  const [username, setUsername] = useState(user.username);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Sync state with props in case user switches accounts quickly
  useEffect(() => {
    if (isOpen) {
      setUsername(user.username);
    }
  }, [isOpen, user]);

  const handleAvatarChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      // Limit file size to 2MB for DB performance
      if (file.size > 2 * 1024 * 1024) {
        alert("Image size too large. Please select an image under 2MB.");
        return;
      }

      const reader = new FileReader();
      reader.onload = (ev) => {
        if (ev.target?.result) {
          onUpdate({ ...user, avatar: ev.target.result as string });
        }
      };
      reader.readAsDataURL(file);
    }
  };

  const handleSave = () => {
    onUpdate({ ...user, username });
    onClose();
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="User Profile">
      <div className="flex flex-col items-center space-y-6">
        <div className="relative group cursor-pointer" onClick={() => fileInputRef.current?.click()}>
          <div className="w-24 h-24 rounded-full overflow-hidden border-2 border-gray-200 bg-gray-100 flex items-center justify-center">
            {user.avatar ? (
              <img src={user.avatar} alt="Avatar" className="w-full h-full object-cover" />
            ) : (
              <span className="text-3xl font-bold text-gray-400 uppercase">{user.username.charAt(0)}</span>
            )}
          </div>
          <div className="absolute inset-0 bg-black/30 rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
            <Upload className="text-white" size={24} />
          </div>
          <input type="file" ref={fileInputRef} className="hidden-input" accept="image/*" onChange={handleAvatarChange} />
        </div>
        
        <div className="w-full space-y-2">
          <label className="text-sm font-medium text-gray-700">Display Name</label>
          <input 
            className="w-full p-3 border rounded-xl bg-gray-50 focus:bg-white transition-colors"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
          />
        </div>

        <div className="w-full space-y-2">
          <label className="text-sm font-medium text-gray-700">Email (ID)</label>
          <div className="w-full p-3 border rounded-xl bg-gray-100 text-gray-500">{user.email}</div>
        </div>

        <div className="flex w-full space-x-3 pt-4">
           <button onClick={onLogout} className="flex-1 border border-red-200 text-red-600 p-3 rounded-xl hover:bg-red-50 flex items-center justify-center space-x-2">
             <LogOut size={18} />
             <span>Sign Out</span>
           </button>
           <button onClick={handleSave} className="flex-1 bg-blue-500 text-white p-3 rounded-xl hover:bg-blue-600">
             Save Changes
           </button>
        </div>
      </div>
    </Modal>
  );
};

const HistoryModal = ({ history, isOpen, onClose, onSelect }: { history: string[], isOpen: boolean, onClose: () => void, onSelect: (q: string) => void }) => (
  <Modal isOpen={isOpen} onClose={onClose} title="Search History">
    {history.length === 0 ? (
      <p className="text-gray-500 text-center py-8">No search history yet.</p>
    ) : (
      <div className="space-y-2 max-h-[400px] overflow-y-auto">
        {history.slice().reverse().map((item, i) => ( // Show newest first
          <button 
            key={i} 
            onClick={() => { onSelect(item); onClose(); }}
            className="w-full flex items-center justify-between p-3 hover:bg-gray-50 rounded-lg text-left group"
          >
            <div className="flex items-center space-x-3">
              <Clock size={16} className="text-gray-400" />
              <span className="text-gray-700 font-medium">{item}</span>
            </div>
            <ArrowRight size={16} className="text-gray-300 group-hover:text-blue-500" />
          </button>
        ))}
      </div>
    )}
  </Modal>
);

// --- Views ---

const DashboardView = ({ 
  user,
  ticker, 
  setTicker, 
  onAnalyze, 
  loading, 
  data, 
  mockChartData,
  onShowHistory,
  triggerAuth
}: { 
  user: UserProfile | null,
  ticker: string, 
  setTicker: (s:string) => void, 
  onAnalyze: () => void, 
  loading: boolean, 
  data: CompanyData | null,
  mockChartData: any[],
  onShowHistory: () => void,
  triggerAuth: () => void
}) => {
  const [showRecent, setShowRecent] = useState(false);
  const [metricHelp, setMetricHelp] = useState<{label: string, text: string, value?: string} | null>(null);

  // Filter recent 10 unique items
  const recentHistory = user ? Array.from(new Set(user.history)).slice(-10).reverse() : [];

  const handleInputFocus = () => {
    if (user && recentHistory.length > 0) setShowRecent(true);
  };

  const selectHistory = (item: string) => {
    setTicker(item);
    setShowRecent(false);
  };

  // Blur delay to allow click
  const handleBlur = () => {
    setTimeout(() => setShowRecent(false), 200);
  };

  const showDefinition = (label: string, value?: string) => {
    const def = METRIC_DEFINITIONS[label];
    if (def) {
      setMetricHelp({ label, text: def, value });
    }
  };

  return (
    <div className="space-y-6 animate-fade-in relative z-0">
      <div className="flex flex-col space-y-4 max-w-2xl mx-auto text-center py-10">
        <h1 className="text-4xl font-semibold tracking-tight text-gray-900">Financial Intelligence.</h1>
        <p className="text-gray-500 text-lg">Instant, AI-powered analysis for any market asset.</p>
        
        <div className="relative group z-20">
          <input 
            type="text" 
            value={ticker}
            onChange={(e) => setTicker(e.target.value)}
            onFocus={handleInputFocus}
            onBlur={handleBlur}
            placeholder={user ? "Enter company code or name (e.g. AAPL, Tesla)" : "Please login to search"}
            className="w-full px-6 py-4 bg-white rounded-2xl text-lg shadow-sm border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500/50 transition-all text-center group-hover:shadow-md"
            onKeyDown={(e) => {
              if (e.key === 'Enter') {
                if (user) {
                   onAnalyze();
                   setShowRecent(false);
                } else {
                   triggerAuth();
                }
              }
            }}
          />
          <button 
            onClick={user ? () => onAnalyze() : triggerAuth}
            disabled={loading || !ticker}
            className="absolute right-3 top-3 bg-blue-500 hover:bg-blue-600 text-white p-2 rounded-xl transition-colors disabled:opacity-50"
          >
            {loading ? <Activity className="animate-spin" size={20} /> : <ArrowRight size={20} />}
          </button>

          {/* Search History Dropdown */}
          {showRecent && recentHistory.length > 0 && (
            <div className="absolute top-full left-0 right-0 mt-2 bg-white/90 backdrop-blur-xl border border-gray-200 rounded-xl shadow-xl overflow-hidden z-30 text-left">
              <div className="p-2">
                 <div className="text-xs text-gray-400 font-semibold px-3 py-2 uppercase tracking-wider">Recent Searches</div>
                 {recentHistory.map((item, idx) => (
                   <button 
                     key={idx} 
                     onClick={() => selectHistory(item)}
                     className="w-full px-3 py-2 hover:bg-blue-50 rounded-lg flex items-center space-x-2 text-gray-700"
                   >
                     <Clock size={14} className="text-gray-400" />
                     <span>{item}</span>
                   </button>
                 ))}
              </div>
              <div className="bg-gray-50 p-2 border-t border-gray-100 flex justify-end">
                <button onMouseDown={onShowHistory} className="text-xs text-blue-600 font-medium hover:underline px-2">
                  View All History
                </button>
              </div>
            </div>
          )}
        </div>
      </div>

      {data && user && (
        <div className="flex flex-col space-y-6">
          {/* Company Overview - Full Width */}
          <Card className="w-full">
            <div className="flex items-center space-x-3 mb-4">
              <div className="bg-blue-100 p-2 rounded-lg text-blue-600">
                <Layers size={20} />
              </div>
              <h2 className="text-xl font-semibold">Overview</h2>
            </div>
            <p className="text-gray-600 leading-relaxed mb-4">{data.summary || "Summary not available."}</p>
            <div className="flex flex-wrap gap-2">
              <span className="px-3 py-1 bg-gray-100 rounded-full text-xs font-medium text-gray-600">{data.sector || "N/A"}</span>
              <span className="px-3 py-1 bg-gray-100 rounded-full text-xs font-medium text-gray-600">{data.ticker || ticker}</span>
            </div>
            <div className="mt-4 pt-4 border-t border-gray-100">
               <h3 className="text-sm font-medium text-gray-900 mb-2">Business Scope</h3>
               <p className="text-sm text-gray-500">{data.businessScope || "N/A"}</p>
            </div>

            {/* Sources Section */}
            {data.sources && data.sources.length > 0 && (
              <div className="mt-4 pt-4 border-t border-gray-100">
                <h3 className="text-sm font-medium text-gray-900 mb-2 flex items-center gap-2">
                   <Search size={14} className="text-gray-400"/> Sources
                </h3>
                <div className="flex flex-wrap gap-2">
                  {data.sources.map((s, i) => (
                    <a key={i} href={s.uri} target="_blank" rel="noopener noreferrer" className="text-xs bg-gray-50 hover:bg-gray-100 text-blue-600 px-2 py-1 rounded border border-gray-200 truncate max-w-[200px] flex items-center gap-1">
                      {s.title} <ExternalLink size={10} />
                    </a>
                  ))}
                </div>
              </div>
            )}
          </Card>

          {/* Key Metrics - Full Width & Grid Layout for Items */}
          <Card className="w-full">
              <div className="flex items-center space-x-3 mb-4">
                 <div className="bg-green-100 p-2 rounded-lg text-green-600">
                  <PieChart size={20} />
                </div>
                <h2 className="text-lg font-semibold">Financial Highlights</h2>
              </div>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <MetricCard 
                  label="P/E Ratio" 
                  value={data.financialHighlights?.peRatio || "N/A"} 
                  onClick={() => showDefinition("P/E Ratio", data.financialHighlights?.peRatio)}
                />
                <MetricCard 
                  label="Market Cap" 
                  value={data.financialHighlights?.marketCap || "N/A"} 
                  onClick={() => showDefinition("Market Cap", data.financialHighlights?.marketCap)}
                />
                <MetricCard 
                  label="Revenue" 
                  value={data.financialHighlights?.revenue || "N/A"} 
                  onClick={() => showDefinition("Revenue", data.financialHighlights?.revenue)}
                />
                <MetricCard 
                  label="Net Income" 
                  value={data.financialHighlights?.netIncome || "N/A"} 
                  onClick={() => showDefinition("Net Income", data.financialHighlights?.netIncome)}
                />
              </div>
          </Card>
            
          {/* Risk Factors - Full Width */}
          <Card className="w-full">
              <div className="flex items-center space-x-3 mb-4">
                 <div className="bg-orange-100 p-2 rounded-lg text-orange-600">
                  <AlertTriangle size={20} />
                </div>
                <h2 className="text-lg font-semibold">Risk Factors</h2>
              </div>
               <ul className="list-disc list-inside text-sm text-gray-600 space-y-2">
                  {(data.risks || []).map((risk, i) => (
                    <li key={i} className="leading-relaxed">{risk}</li>
                  ))}
               </ul>
          </Card>

          {/* Chart Section - Full Width */}
          <Card className="w-full">
             <div className="flex items-center justify-between mb-6">
              <div className="flex items-center space-x-3">
                <div className="bg-purple-100 p-2 rounded-lg text-purple-600">
                  <TrendingUp size={20} />
                </div>
                <div>
                  <h2 className="text-xl font-semibold">Market Analysis</h2>
                  <p className="text-xs text-gray-400">Simulated real-time data visualization</p>
                </div>
              </div>
              <div className="flex space-x-2">
                 <span className="text-xs bg-gray-100 px-2 py-1 rounded text-gray-500">MA</span>
                 <span className="text-xs bg-gray-100 px-2 py-1 rounded text-gray-500">RSI</span>
                 <span className="text-xs bg-gray-100 px-2 py-1 rounded text-gray-500">MACD</span>
              </div>
             </div>
             
             <div className="w-full mt-4">
                <SimpleChart data={mockChartData} />
             </div>
             
             {/* Updated Grid for Market Analysis Stats to prevent overflow/squashing */}
             <div className="grid grid-cols-2 md:grid-cols-3 gap-4 mt-6">
               <div className="text-center">
                  <HoverTooltip text={INDICATOR_DEFINITIONS['RSI']}>
                    <div className="text-xs text-gray-400 mb-1 border-b border-dashed border-gray-300 inline-block">RSI (14)</div>
                  </HoverTooltip>
                  <div className="font-mono font-medium text-gray-700">{mockChartData.length > 0 ? mockChartData[mockChartData.length-1].rsi.toFixed(2) : '-'}</div>
               </div>
               <div className="text-center">
                  <HoverTooltip text={INDICATOR_DEFINITIONS['MACD']}>
                    <div className="text-xs text-gray-400 mb-1 border-b border-dashed border-gray-300 inline-block">MACD</div>
                  </HoverTooltip>
                  <div className="font-mono font-medium text-gray-700">{mockChartData.length > 0 ? mockChartData[mockChartData.length-1].macd.toFixed(2) : '-'}</div>
               </div>
               <div className="text-center">
                  <HoverTooltip text={INDICATOR_DEFINITIONS['MA20']}>
                    <div className="text-xs text-gray-400 mb-1 border-b border-dashed border-gray-300 inline-block">MA (20)</div>
                  </HoverTooltip>
                  <div className="font-mono font-medium text-gray-700">{mockChartData.length > 0 ? mockChartData[mockChartData.length-1].ma20.toFixed(2) : '-'}</div>
               </div>
               <div className="text-center">
                  <HoverTooltip text={INDICATOR_DEFINITIONS['Volume']}>
                    <div className="text-xs text-gray-400 mb-1 border-b border-dashed border-gray-300 inline-block">Volume</div>
                  </HoverTooltip>
                  <div className="font-mono font-medium text-gray-700">{mockChartData.length > 0 ? (mockChartData[mockChartData.length-1].volume / 1000).toFixed(1) + 'K' : '-'}</div>
               </div>
                <div className="text-center">
                  <HoverTooltip text={INDICATOR_DEFINITIONS['Stoch']}>
                    <div className="text-xs text-gray-400 mb-1 border-b border-dashed border-gray-300 inline-block">Stoch %K</div>
                  </HoverTooltip>
                  <div className="font-mono font-medium text-gray-700">{mockChartData.length > 0 ? mockChartData[mockChartData.length-1].stochK.toFixed(1) : '-'}</div>
               </div>
               <div className="text-center">
                  <HoverTooltip text={INDICATOR_DEFINITIONS['Bollinger']}>
                    <div className="text-xs text-gray-400 mb-1 border-b border-dashed border-gray-300 inline-block">Bollinger (Up/Lo)</div>
                  </HoverTooltip>
                  <div className="font-mono font-medium text-gray-700 text-xs mt-1">
                    {mockChartData.length > 0 ? (
                      <>
                        <div>{mockChartData[mockChartData.length-1].bollUpper.toFixed(2)}</div>
                        <div className="text-gray-400">{mockChartData[mockChartData.length-1].bollLower.toFixed(2)}</div>
                      </>
                    ) : '-'}
                  </div>
               </div>
             </div>
          </Card>
          
           {/* Market Prediction - Full Width (New Section) */}
           {data.prediction && <PredictionCard prediction={data.prediction} />}
        </div>
      )}

      {/* Guest State Message */}
      {!user && (
        <div className="text-center py-10">
          <p className="text-gray-400 mb-4">Sign in to access advanced AI analysis, history, and real-time insights.</p>
          <button onClick={triggerAuth} className="text-blue-600 font-medium hover:underline">Create an account or Sign In</button>
        </div>
      )}

      {/* Metric Definition Modal */}
      <Modal 
        isOpen={!!metricHelp} 
        onClose={() => setMetricHelp(null)} 
        title={metricHelp?.label || ""}
      >
        <div className="flex flex-col space-y-4">
          {metricHelp?.value && (
            <div className="bg-gray-50 p-4 rounded-xl border border-gray-100 text-center">
              <div className="text-sm text-gray-500 mb-1 uppercase tracking-wider">Current Value</div>
              <div className="text-3xl font-bold text-gray-900">{metricHelp.value}</div>
            </div>
          )}
          <div className="flex items-start space-x-4">
            <div className="bg-blue-100 p-3 rounded-full text-blue-600 shrink-0">
              <Info size={24} />
            </div>
            <div>
              <p className="text-gray-600 leading-relaxed text-sm md:text-base">
                {metricHelp?.text}
              </p>
            </div>
          </div>
        </div>
        <div className="mt-6 flex justify-end">
          <button 
            onClick={() => setMetricHelp(null)}
            className="px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-800 rounded-lg text-sm font-medium transition-colors"
          >
            Close
          </button>
        </div>
      </Modal>
    </div>
  );
};

// --- App Component ---

const App = () => {
  const [user, setUser] = useState<UserProfile | null>(null);
  const [activeTab, setActiveTab] = useState('dashboard');
  const [authModalOpen, setAuthModalOpen] = useState(false);
  const [profileModalOpen, setProfileModalOpen] = useState(false);
  const [historyModalOpen, setHistoryModalOpen] = useState(false);
  
  const [ticker, setTicker] = useState('');
  const [data, setData] = useState<CompanyData | null>(null);
  const [loading, setLoading] = useState(false);
  const [mockChartData, setMockChartData] = useState<any[]>([]);

  // Initialize DB and Check for Active Session
  useEffect(() => {
    const initApp = async () => {
      try {
        await dbService.init();
        const cachedEmail = localStorage.getItem(SESSION_KEY);
        if (cachedEmail) {
          const cachedUser = await dbService.getUser(cachedEmail);
          if (cachedUser) {
            setUser(cachedUser);
          }
        }
      } catch (e) {
        console.error("Initialization failed", e);
      }
    };
    initApp();
  }, []);

  const handleLoginSuccess = (u: UserProfile) => {
    setUser(u);
    localStorage.setItem(SESSION_KEY, u.email); // Persist session
    setAuthModalOpen(false);
  };

  const handleAnalyze = async (tickerOverride?: string) => {
    const searchTicker = typeof tickerOverride === 'string' ? tickerOverride : ticker;
    if (!searchTicker) return;
    
    if (tickerOverride && tickerOverride !== ticker) {
        setTicker(tickerOverride);
    }
    
    setLoading(true);
    setData(null);
    setMockChartData([]);

    try {
      const response = await ai.models.generateContent({
        model: 'gemini-3-flash-preview',
        contents: `Analyze the company with ticker or name: "${searchTicker}". Provide a comprehensive financial summary, key metrics, risk factors, and a market trend prediction for the next 3 months (target price, trend, confidence, reasoning).`,
        config: {
          responseMimeType: 'application/json',
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              name: { type: Type.STRING },
              ticker: { type: Type.STRING },
              summary: { type: Type.STRING },
              sector: { type: Type.STRING },
              businessScope: { type: Type.STRING },
              financialHighlights: {
                type: Type.OBJECT,
                properties: {
                  peRatio: { type: Type.STRING },
                  pbRatio: { type: Type.STRING },
                  marketCap: { type: Type.STRING },
                  revenue: { type: Type.STRING },
                  netIncome: { type: Type.STRING },
                  grossMargin: { type: Type.STRING },
                  debtToAsset: { type: Type.STRING },
                }
              },
              risks: {
                type: Type.ARRAY,
                items: { type: Type.STRING }
              },
              prediction: {
                type: Type.OBJECT,
                properties: {
                  targetPrice: { type: Type.STRING },
                  trend: { type: Type.STRING, enum: ["Bullish", "Bearish", "Neutral"] },
                  confidence: { type: Type.INTEGER },
                  horizon: { type: Type.STRING },
                  reasoning: { type: Type.STRING }
                }
              }
            }
          },
          tools: [{ googleSearch: {} }]
        }
      });
      
      const jsonText = response.text;
      if (jsonText) {
        const parsedData = JSON.parse(jsonText);
        
        // Extract grounding metadata if available
        const groundingChunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks;
        const sources = groundingChunks
            ?.map((chunk: any) => chunk.web)
            .filter((web: any) => web) || [];

        const finalData = { ...parsedData, sources };
        setData(finalData);

        if (user) {
          // Remove duplicates if existing, push new to end
          const newHistory = [...user.history.filter(h => h !== searchTicker), searchTicker];
          const updatedUser = { ...user, history: newHistory };
          await dbService.saveUser(updatedUser);
          setUser(updatedUser);
        }

        setMockChartData(generateMockStockData(150, 30)); 
      }

    } catch (error) {
      console.error("Analysis failed:", error);
      alert("Failed to analyze. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const handleUpdateProfile = async (updatedUser: UserProfile) => {
    await dbService.saveUser(updatedUser);
    setUser(updatedUser);
  };

  const handleLogout = () => {
    localStorage.removeItem(SESSION_KEY); // Remove persistence
    setUser(null);
    setAuthModalOpen(false);
    setData(null);
    setTicker('');
    setMockChartData([]); // Explicitly clear chart data
    setActiveTab('dashboard'); // Reset view to dashboard
  };

  return (
    <div className="flex h-screen bg-gray-50 font-sans text-gray-900 selection:bg-blue-100 selection:text-blue-900">
      <div className="w-64 bg-white/80 backdrop-blur-xl border-r border-gray-200 flex flex-col justify-between hidden md:flex z-10 shadow-[4px_0_24px_-12px_rgba(0,0,0,0.1)]">
        <div className="p-6">
          <div className="flex items-center space-x-3 text-blue-600 mb-10">
             <div className="bg-gradient-to-tr from-blue-600 to-blue-500 text-white p-2.5 rounded-xl shadow-lg shadow-blue-500/20">
               <Activity size={24} />
             </div>
             <span className="text-xl font-bold tracking-tight text-gray-900">AlphaAnalyst</span>
          </div>
          
          <nav className="space-y-2">
            <SidebarItem icon={Layers} label="Dashboard" active={activeTab === 'dashboard'} onClick={() => setActiveTab('dashboard')} />
            <SidebarItem icon={History} label="History" active={false} onClick={() => setHistoryModalOpen(true)} disabled={!user} />
          </nav>
        </div>

        <div className="p-4 border-t border-gray-100 bg-white/50 backdrop-blur-md">
          {user ? (
            <div 
              onClick={() => setProfileModalOpen(true)}
              className="flex items-center space-x-3 p-3 rounded-xl hover:bg-white/80 hover:shadow-sm cursor-pointer transition-all duration-200 border border-transparent hover:border-gray-100"
            >
              <div className="w-10 h-10 rounded-full bg-gradient-to-br from-blue-100 to-blue-50 text-blue-600 flex items-center justify-center font-bold shadow-inner">
                {user.avatar ? <img src={user.avatar} className="w-full h-full rounded-full object-cover"/> : user.username.charAt(0)}
              </div>
              <div className="flex-1 min-w-0">
                <div className="text-sm font-semibold text-gray-900 truncate">{user.username}</div>
                <div className="text-xs text-gray-500 truncate">{user.email}</div>
              </div>
            </div>
          ) : (
            <button 
              onClick={() => setAuthModalOpen(true)}
              className="w-full bg-gray-900 text-white p-3 rounded-xl font-medium text-sm hover:bg-gray-800 transition-all shadow-lg shadow-gray-200 flex items-center justify-center space-x-2"
            >
              <User size={18} />
              <span>Sign In</span>
            </button>
          )}
        </div>
      </div>

      <div className="flex-1 flex flex-col h-screen overflow-hidden relative">
        <main className="flex-1 overflow-y-auto p-6 md:p-12 scroll-smooth">
          <div className="max-w-5xl mx-auto">
             {activeTab === 'dashboard' && (
               <DashboardView 
                 key={user ? user.email : 'guest'} // Force remount on user change to reset all internal state
                 user={user}
                 ticker={ticker}
                 setTicker={setTicker}
                 onAnalyze={() => handleAnalyze()}
                 loading={loading}
                 data={data}
                 mockChartData={mockChartData}
                 onShowHistory={() => setHistoryModalOpen(true)}
                 triggerAuth={() => setAuthModalOpen(true)}
               />
             )}
          </div>
        </main>
      </div>

      <AuthModal isOpen={authModalOpen} onClose={() => setAuthModalOpen(false)} onLoginSuccess={handleLoginSuccess} />
      
      {user && (
        <>
          <ProfileModal 
            key={user.email} // Ensure modal logic resets on user switch
            user={user} 
            isOpen={profileModalOpen} 
            onClose={() => setProfileModalOpen(false)} 
            onUpdate={handleUpdateProfile}
            onLogout={handleLogout}
          />
          <HistoryModal 
            key={user.email + '_history'} // Ensure history state is fresh
            history={user.history} 
            isOpen={historyModalOpen} 
            onClose={() => setHistoryModalOpen(false)} 
            onSelect={(t) => handleAnalyze(t)} 
          />
        </>
      )}
    </div>
  );
};

const root = createRoot(document.getElementById("root"));
root.render(<App />);